name: Executar API

on:
  schedule:
    - cron: '17 10 * * *'  # 07:17 Brasil
    - cron: '17 16 * * *'  # 13:17 Brasil
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: api-pipeline
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas gspread oauth2client google-api-python-client google-auth

      - name: Create credentials file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > teste-477018-5cb1426a435b.json

      - name: Run script
        run: python API_MB1.py
        env:
          TOKEN_SGA: ${{ secrets.TOKEN_SGA }}
          USUARIO_API: ${{ secrets.USUARIO_API }}
          SENHA_API: ${{ secrets.SENHA_API }}
          TOKEN_CRM: ${{ secrets.TOKEN_CRM }}
